/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author straight
 */
public class posttestmodul2 extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator
     */
    float akhir;
    public posttestmodul2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grubhitung = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nilaix = new javax.swing.JTextField();
        nilaiy = new javax.swing.JTextField();
        rdtambah = new javax.swing.JRadioButton();
        rdkali = new javax.swing.JRadioButton();
        rdkurang = new javax.swing.JRadioButton();
        rdbagi = new javax.swing.JRadioButton();
        btnhitung = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nilai X");

        jLabel2.setText("Nilai Y");

        grubhitung.add(rdtambah);
        rdtambah.setText("Tambah");
        rdtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtambahActionPerformed(evt);
            }
        });

        grubhitung.add(rdkali);
        rdkali.setText("Kali");
        rdkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdkaliActionPerformed(evt);
            }
        });

        grubhitung.add(rdkurang);
        rdkurang.setText("Kurang");
        rdkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdkurangActionPerformed(evt);
            }
        });

        grubhitung.add(rdbagi);
        rdbagi.setText("Bagi");
        rdbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbagiActionPerformed(evt);
            }
        });

        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jLabel3.setText("Hasil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nilaiy, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(nilaix)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdtambah)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhitung)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(hasil, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdkurang)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdkali)))
                                .addGap(18, 18, 18)
                                .addComponent(rdbagi)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nilaix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nilaiy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdtambah)
                    .addComponent(rdkali)
                    .addComponent(rdkurang)
                    .addComponent(rdbagi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhitung)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtambahActionPerformed
        // TODO add your handling code here:
        if(rdtambah.isSelected())
        {
        float x,y;
        x = Float.parseFloat(nilaix.getText());
        y = Float.parseFloat(nilaiy.getText());
        akhir=x+y;
        }
    }//GEN-LAST:event_rdtambahActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        hasil.setText(Float.toString(akhir));
    }//GEN-LAST:event_btnhitungActionPerformed

    private void rdkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdkurangActionPerformed
        // TODO add your handling code here:
        if(rdkurang.isSelected())
        {
        float x,y;
        x = Float.parseFloat(nilaix.getText());
        y = Float.parseFloat(nilaiy.getText());
        akhir=x-y;
        }
    }//GEN-LAST:event_rdkurangActionPerformed

    private void rdkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdkaliActionPerformed
        // TODO add your handling code here:
        if(rdkali.isSelected())
        {
        float x,y;
        x = Float.parseFloat(nilaix.getText());
        y = Float.parseFloat(nilaiy.getText());
        akhir=x*y;
        }
    }//GEN-LAST:event_rdkaliActionPerformed

    private void rdbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbagiActionPerformed
        // TODO add your handling code here:
        if(rdbagi.isSelected())
        {
        float x,y;
        x = Float.parseFloat(nilaix.getText());
        y = Float.parseFloat(nilaiy.getText());
        akhir=x/y;
        }
    }//GEN-LAST:event_rdbagiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(posttestmodul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(posttestmodul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(posttestmodul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(posttestmodul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new posttestmodul2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.ButtonGroup grubhitung;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nilaix;
    private javax.swing.JTextField nilaiy;
    private javax.swing.JRadioButton rdbagi;
    private javax.swing.JRadioButton rdkali;
    private javax.swing.JRadioButton rdkurang;
    private javax.swing.JRadioButton rdtambah;
    // End of variables declaration//GEN-END:variables
}
